<script setup>
import { onMounted,ref,computed } from 'vue'
import { api } from '../api'
const items=ref([]),busy=ref(true),error=ref(''),module=ref(''),q=ref('')
const modules=computed(()=>[...new Set(items.value.map(c=>c.module))])
const groups=computed(()=>{const out={};for(const c of items.value.filter(c=>(!module.value||c.module===module.value)&&(!q.value||c.name.includes(q.value)))){const key=c.module+' / '+c.secondary;(out[key]??=[]).push(c)}return out})
async function load(){busy.value=true;try{items.value=await api.concepts({})}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(load)
</script>
<template><div class="page-heading"><div><p class="eyebrow">考点地图 / KNOWLEDGE MAP</p><h1>让题目，连成知识</h1><p class="muted">沿着模块与题型，找到考点边界和易混之处。</p></div><span class="map-count">{{ items.length }} <small>个已归纳考点</small></span></div><div class="notice info">这里展示已有标注覆盖的考点与真实题量。全量标注会在网站部署后逐步补充。</div><div class="filters"><label>模块<select v-model="module"><option value="">全部模块</option><option v-for="m in modules" :key="m">{{ m }}</option></select></label><label class="search-field">考点名称<input v-model="q" placeholder="例如：基期量、加强削弱" /></label></div><p v-if="error" class="notice err" role="alert">{{ error }} <button @click="load">重试</button></p><p v-if="busy" class="empty" role="status">正在整理考点…</p><section v-for="(list,key) in groups" v-else :key="key" class="concept-section"><div class="concept-section-heading"><h2>{{ key }}</h2><span class="muted">{{ list.length }} 个考点</span></div><div class="concept-grid"><RouterLink v-for="c in list" :key="c.id" :to="`/concepts/${c.id}`" class="concept-card"><span class="small-label">{{ c.secondary }}</span><h3>{{ c.name.replace(c.secondary+'-','') }}</h3><div class="concept-card-footer"><span>{{ c.question_count }} 道真题</span><span aria-hidden="true">↗</span></div><div v-if="c.answered" class="mastery"><div class="progress"><span :style="{width:Math.round(c.mastery*100)+'%'}" /></div><span class="small">已答 {{ c.answered }} 次 · 正确率 {{ Math.round(c.mastery*100) }}%</span></div></RouterLink></div></section><div v-if="!busy&&!Object.keys(groups).length" class="empty">暂无匹配考点。可以先到题库选择模块练习。</div></template>
