<script setup>
import { onMounted,ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { api } from '../api'
import RichText from '../components/RichText.vue'
import QuestionRows from '../components/QuestionRows.vue'
const route=useRoute(),router=useRouter(),concept=ref(null),error=ref(''),busy=ref(true),starting=ref(false)
async function start(id){starting.value=true;try{const s=await api.createSession(id?'single':'concept',id?{question_ids:[id]}:{concept_id:concept.value.id,limit:20});await router.push(`/practice?session=${s.session_id}`)}catch(e){error.value=e.message}finally{starting.value=false}}
onMounted(async()=>{try{concept.value=await api.concept(route.params.id)}catch(e){error.value=e.message}finally{busy.value=false}})
</script>
<template><RouterLink class="back-link" to="/concepts">← 返回考点地图</RouterLink><p v-if="error" class="notice err" role="alert">{{ error }}</p><p v-if="busy" class="empty" role="status">正在加载考点…</p><template v-if="concept"><div class="page-heading"><div><p class="eyebrow">{{ concept.module }} / {{ concept.secondary }}</p><h1>{{ concept.name }}</h1><p class="muted">已有标注覆盖 {{ concept.question_count }} 道真题</p></div><button class="primary" :disabled="starting||!concept.question_count" @click="start()">围绕这个考点练习</button></div><div class="notice info">卡片由现有题目标注提供参考，尚未经全量聚合审查。具体题目的解法与疑点会在作答后展示。</div><div class="concept-detail-grid"><section v-for="[key,title] in [['question_model','问法模型'],['template','母题抽象'],['key_features','识别特征'],['boundary','适用边界'],['typical_ask','典型提问']]" :key="key" class="panel concept-detail-card"><p class="small-label">{{ title }}</p><template v-if="Array.isArray(concept.card[key])"><ul><li v-for="(v,i) in concept.card[key]" :key="i"><RichText :text="v" /></li></ul></template><RichText v-else-if="concept.card[key]" :text="concept.card[key]" /><p v-else class="muted">暂无归纳内容。</p></section></div><section class="panel related"><div class="panel-heading"><h2>易混考点与区分信号</h2></div><article v-for="(v,i) in concept.related" :key="i"><RouterLink v-if="v.concept_id" :to="`/concepts/${v.concept_id}`">{{ v.name }} ↗</RouterLink><strong v-else>{{ v.name }}</strong><RichText :text="v.signal" /></article><p v-if="!concept.related.length" class="empty">暂无易混考点记录。</p></section><section class="panel"><div class="panel-heading"><h2>从实例中理解</h2><RouterLink :to="`/questions?concept_id=${concept.id}`">查看全部真题 →</RouterLink></div><QuestionRows :items="concept.sample_questions" :busy="starting" @practice="start" /></section><p class="muted small">卡片参考来源：{{ concept.card.model }} · {{ concept.card.run_id }}</p></template></template>
