<script setup>
import { onMounted,ref } from 'vue'
import { api } from '../api'
import Pagination from '../components/Pagination.vue'
const stats=ref({answered:0,correct:0,wrong:0,favorites:0,sessions:0}),data=ref({items:[],total:0}),page=ref(1),busy=ref(true),error=ref('')
const kinds={single:'专项练习',paperset:'真题试卷',concept:'考点练习',wrongbook:'错题复练',favorite:'收藏练习'}
function date(s){return new Date(s).toLocaleString('zh-CN',{hour12:false})}
async function load(p=1){page.value=p;busy.value=true;error.value='';try{[stats.value,data.value]=await Promise.all([api.stats(),api.records({limit:20,offset:(p-1)*20})])}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(()=>load())
</script>
<template><div class="page-heading"><div><p class="eyebrow">学习记录 / LEARNING JOURNAL</p><h1>每一步，都算数</h1><p class="muted">从练习记录里回顾进步，也可以继续未完成的练习。</p></div><RouterLink class="button primary" to="/questions">开始新的练习</RouterLink></div><div class="stats-grid"><article><span>累计作答</span><strong>{{ stats.answered }} <small>次</small></strong></article><article><span>作答正确率</span><strong>{{ stats.answered ? Math.round(stats.correct/stats.answered*100) : 0 }}<small>%</small></strong></article><article><span>待订正题</span><strong>{{ stats.wrong }} <small>题</small></strong></article><article><span>我的收藏</span><strong>{{ stats.favorites || 0 }} <small>题</small></strong></article><article><span>完成练习</span><strong>{{ stats.sessions }} <small>份</small></strong></article></div><p v-if="error" class="notice err" role="alert">{{ error }}</p><section class="panel"><div class="panel-heading"><h2>练习记录</h2></div><p v-if="busy" class="empty" role="status">正在加载学习记录…</p><div v-else class="record-list"><article v-for="p in data.items" :key="p.session_id"><div><span class="small-label">{{ date(p.started_at) }}</span><h3>{{ kinds[p.kind] }} <span class="tag">{{ p.submitted_at ? '已完成' : '进行中' }}</span></h3><p class="muted">{{ p.total }} 题<template v-if="p.submitted_at"> · 答对 {{ p.correct }} 题 · {{ Math.round(p.duration_ms/60000) }} 分钟</template></p></div><RouterLink class="button" :to="`/practice?session=${p.session_id}`">{{ p.submitted_at?'查看复盘':'继续练习' }} →</RouterLink></article></div><div v-if="!busy&&!data.items.length" class="empty"><h3>第一份学习记录，等你写下</h3><RouterLink to="/questions">选择模块，开始练习</RouterLink></div><Pagination :page="page" :size="20" :total="data.total" :busy="busy" @change="load" /></section></template>
