<script setup>
import { ref,computed,watch } from 'vue'
const props=defineProps({items:{type:Array,default:()=>[]}})
const selected=ref(0),hovered=ref(null),root=ref(null)
watch(()=>props.items,items=>{selected.value=Math.max(0,items.length-1);hovered.value=null},{immediate:true})
const current=computed(()=>props.items[hovered.value??selected.value])
const active=computed(()=>props.items.filter(v=>v.answered>0).length)
const offset=computed(()=>props.items[0]?(new Date(props.items[0].date+'T00:00:00Z').getUTCDay()+6)%7:0)
const level=v=>v===0?0:v<5?1:v<20?2:v<50?3:4
function move(e){if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key))return;e.preventDefault();hovered.value=null;const step={ArrowLeft:-7,ArrowRight:7,ArrowUp:-1,ArrowDown:1}[e.key];selected.value=e.key==='Home'?0:e.key==='End'?props.items.length-1:Math.max(0,Math.min(props.items.length-1,selected.value+step));root.value?.querySelectorAll('button')[selected.value]?.focus()}
</script>
<template><section class="pc-card pc-chart pc-calendar" data-chart="activity"><div class="pc-card-heading"><div><h2>90 日学习日历</h2><p class="muted small">{{ items[0]?.date }} 至 {{ items.at(-1)?.date }} · {{ active }} 个作答日</p></div><span class="pc-tag">北京时间</span></div><div class="pc-calendar-scroll"><div class="pc-calendar-weekdays" aria-hidden="true"><span v-for="day in ['一','二','三','四','五','六','日']" :key="day">{{ day }}</span></div><div class="pc-calendar-grid" ref="root" role="group" aria-label="学习日历，左右键跨七天，上下键选择相邻日期" @keydown="move"><span v-for="i in offset" :key="'padding'+i" aria-hidden="true"/><button v-for="(day,i) in items" :key="day.date" :class="['pc-day',`pc-day-${level(day.answered)}`,{'pc-day-selected':selected===i}]" :tabindex="selected===i?0:-1" :aria-label="`${day.date}，${day.answered} 次作答，${(day.duration_ms/60000).toFixed(1)} 分钟`" :aria-pressed="selected===i" @click="selected=i;hovered=null" @focus="selected=i;hovered=null" @mouseenter="hovered=i" @mouseleave="hovered=null"><span>{{ day.date.slice(8) }}</span></button></div></div><div class="pc-calendar-legend"><span>作答次数</span><span v-for="(name,i) in ['0','1–4','5–19','20–49','50+']" :key="i"><i :class="`pc-day-${i}`"/>{{ name }}</span></div><p class="pc-chart-value" v-if="current" role="status">{{ current.date }} · {{ current.answered }} 次作答 · {{ (current.duration_ms/60000).toFixed(1) }} 分钟 · {{ current.sessions }} 份已提交练习</p><details class="pc-table-details"><summary>查看活动日数据表</summary><div class="pc-table-scroll"><table class="data-table data-table--compact"><caption>最近 90 日作答活动</caption><thead><tr><th>日期</th><th>作答次数</th><th>分钟</th><th>练习数</th></tr></thead><tbody><tr v-for="day in items" :key="day.date"><td>{{ day.date }}</td><td>{{ day.answered }}</td><td>{{ (day.duration_ms/60000).toFixed(1) }}</td><td>{{ day.sessions }}</td></tr></tbody></table></div></details></section></template>
